### ISSUE TITLE
KeyNotFoundException when using Get with predicate

### ISSUE THREAD

**Issue by sakopov** [tmsmith/Dapper-Extensions#107]
Querying Postgres via Npgsql. Here is the model with class mapper.

```
    public class Audience
    {
        public int Id { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public DateTime ClientSecretExpiresOn { get; set; }
        public string ClientName { get; set; }
        public string RedirectUrl { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime ModifiedOn { get; set; }
        public DateTime? DeletedOn { get; set; }
    }

    public class AudienceMapper : ClassMapper<Audience>
    {
        public AudienceMapper()
        {
            base.Table("audiences");
            Map(column => column.Id).Column("audience_id").Key(KeyType.Identity);
            Map(column => column.ClientId).Column("client_id");
            Map(column => column.ClientSecret).Column("client_secret");
            Map(column => column.ClientSecretExpiresOn).Column("client_secret_expiration_date");
            Map(column => column.RedirectUrl).Column("redirect_uri");
            Map(column => column.CreatedOn).Column("created_date");
            Map(column => column.ModifiedOn).Column("modified_date");
            Map(column => column.DeletedOn).Column("deleted_date");
        }
    }
```

Here is the repo.

```
    public class AudienceRepository
    {
        public AudienceRepository()
        {
            DapperExtensions.DapperExtensions.DefaultMapper = typeof(AudienceMapper);
            DapperExtensions.DapperExtensions.SqlDialect = new PostgreSqlDialect();
        }

        public Audience GetByClientId(string clientId)
        {
            using (var conn = new PostgreSqlConnectionFactory().Create(ConnectionStrings.IdentityProvider))
            {
                conn.Open();

                var predicate = Predicates.Field<Audience>(f => f.ClientId, Operator.Eq, clientId);

                var audience = conn.Get<Audience>(predicate); // Bomb

                conn.Close();

                return audience;
            }
        }
    }
```

Stack Trace

```
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DapperExtensions.DapperImplementor.GetIdPredicate(IClassMapper classMap, Object id) in c:\Projects\Nuget\PhenixDev\DapperExtensions\DapperExtensions\DapperImplementor.cs:line 283
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at DapperExtensions.DapperImplementor.Get[T](IDbConnection connection, Object id, IDbTransaction transaction, Nullable`1 commandTimeout) in c:\Projects\Nuget\PhenixDev\DapperExtensions\DapperExtensions\DapperImplementor.cs:line 41
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at DapperExtensions.DapperExtensions.Get[T](IDbConnection connection, Object id, IDbTransaction transaction, Nullable`1 commandTimeout) in c:\Projects\Nuget\PhenixDev\DapperExtensions\DapperExtensions\DapperExtensions.cs:line 139
   at IdentityProvider.Api.Persistence.AudienceRepository.GetByClientId(String clientId) in c:\Tfs\IdentityProvider\Source\IdentityProvider.Api\Persistence\AudienceRepository.cs:line 25
   at IdentityProvider.Api.Endpoints.Clients.ClientsController.Post(AudiencePostViewModel audience) in c:\Tfs\IdentityProvider\Source\IdentityProvider.Api\Endpoints\Clients\ClientsController.cs:line 26
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

I'm thinking this has something to do with the class map. I honestly don't fully understand how to actually apply the class map. Assigning it to DefaultMapper in every repo seems like a horrible idea and I'm hoping there is a better way to do this.

**Comment by RubSteels** [comment]
Any news on the issue?

**Comment by jdiosdado** [comment]
The reason why you are getting this is because predicates can only be used with GetList, the only reason why the compiler does not complain is because Get accepts a dynamic type as the first argument:
```C#
public static T Get<T>(this IDbConnection connection, dynamic id, ...
```
Get  works only when you provide the id, for predicates use GetList and then FirstOrDefault or whatever you need.

**Comment by MaurGi** [comment]
Happened to me as well, it is hard to understand why because the code looks ok - should Get<T> throw an exception when a Predicate is passed?
Happy to submit the following:

```
public T Get<T>(IDbConnection connection, dynamic id, IDbTransaction transaction, int? commandTimeout) where T : class
{
    if (id is IPredicate)
    {
        throw new ArgumentException("Predicates work for GetList<T>, not for Get<T>");
    }
    IClassMapper classMap = SqlGenerator.Configuration.GetMap<T>();
    IPredicate predicate = GetIdPredicate(classMap, id);
    T result = GetList<T>(connection, classMap, predicate, null, transaction, commandTimeout, true).SingleOrDefault();
    return result;
}
```

**Comment by aluanhaddad** [comment]
@MaurGi That is a great point, but we can do even better and make it a compile time error

```C#
public static T Get<T>(this IDbConnection connection, dynamic id, IDbTransaction transaction, int? commandTimeout = null) where T : class

[Obsolete("Predicates work for GetList<T>, not for Get<T>", error: true)]
public static T Get<T>(this IDbConnection connection, IPredicate id, IDbTransaction transaction, int? commandTimeout = null) where T : class

// ...

using (var connection = new SqlConnection())
using (var transaction = connection.BeginTransaction())
{
    // Compile time error.
    connection.Get<MyEntity>(predicates.Field<MyEntity>(e => e.Id, Operator.Eq, 1), transaction);
}
```

**Comment by valfrid-ly** [comment]
Obsolete won't get you compile error, just warning. It's possible to do it but it will be only a warning and runtime error.
