### ISSUE TITLE
Problems with class mapper

### ISSUE THREAD

**Issue by leonardopottmayer** [tmsmith/Dapper-Extensions#323]
Hello. I'm having some trouble while trying to use ClassMapper...

My entity class:

```
public class Product : AuditableEntity
    {
        public Product() { }
        public Product(int id, string name, decimal price)
        {
            Id = id;
            Name = name;
            Price = price;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    }
```
My mapper class:

```
public class ProductMapper : AuditableEntityClassMapper<Product>
    {
        public ProductMapper()
        {
            Table("product");

            Map(i => i.Id).Column("id").Key(KeyType.Identity);
            Map(i => i.Name).Column("name_desc");
            Map(i => i.Price).Column("price");
        }
    }
```

Additional class:

```
public abstract class AuditableEntityClassMapper<TEntity> : ClassMapper<TEntity> where TEntity : AuditableEntity
    {
        public AuditableEntityClassMapper()
        {
            Map(i => i.CreatedBy).Column("created_by");
            Map(i => i.CreatedAt).Column("created_at");
            Map(i => i.UpdatedBy).Column("updated_by");
            Map(i => i.UpdatedAt).Column("updated_at");
        }
    }
```

The stacktrace it generates:

```
MySqlConnector.MySqlException (0x80004005): Unknown column 'y_1.Name' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
```

It seems like it's ignoring the .Column() method in class mapper and it's generating the SQL sentence based on the class attributes. There's an example in stacktrace, with "Name" and "name_desc". But the same error happens with "CreatedAt" and "created_at", "UpdatedBy" and "updated_by", etc.

**Comment by code-chump** [comment]
Out of curiosity were you calling GetSet<T> when you had that error?

It looks like [this commit](https://github.com/tmsmith/Dapper-Extensions/commit/e1cb1b14a70bb8ba969c913774245bccd955c83a#diff-3e96a76bab119f8da9e5b488dac60345c8fad90dc28ae0f66ef62ca4b74b6e97) introduced aliases on SELECT columns for the three primary 'get' pathways GetList, GetPage, and GetSet but while the GetList and GetPage implementations take the result from Dapper and apply mapping to remove the aliases, GetSet just returns the result.

This was probably missed at the time because the integration tests don't cover GetSet, but it is surprising that this is the only issue that's been raised for it.
